# Generated by Django 5.0.1 on 2024-01-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_alter_product_category_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='regular_price',
            new_name='price',
        ),
    ]
