# Generated by Django 5.0 on 2024-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_product_description_alter_product_brandname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandName',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='regularPrice',
            new_name='regular_price',
        ),
    ]
